Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'DIU.Neos.Content.Picture': ['*','NodeTypes/*']
    fusion:
      autoInclude:
        'DIU.Neos.Content.Picture': true
    nodeTypes:
      groups:
        module:
          position: 'start'
          label: Module
          collapsed: false